aws_region      = "ap-northeast-1"
project_name    = "bolt-oscar-app"
vpc_cidr        = "10.0.0.0/16"
# container_image = "makisunwood/bolt:latest"
# container_image = "makisunwood/bolt:v0.3.7"
container_image = "498218886114.dkr.ecr.ap-northeast-1.amazonaws.com/bolt-oscar-app:latest"
task_cpu        = "1024"    # 1 vCPU
task_memory     = "2048"    # 2GB
app_count       = 1
